spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsf_example?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  flyway:
    enabled: true

lsf:
  outbox:
    enabled: true
    table: lsf_outbox
